trigger:
  none
stages:
- stage: __default
  jobs:
  - job: Job
    pool:
      vmImage: macOS-latest
    steps:
    - task: JavaToolInstaller@0
      inputs:
        versionSpec: '17'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'PreInstalled'
    - task: Bash@3
      displayName: Check SDK
      inputs:
        targetType: 'inline'
        script: |
          #!/usr/bin/env bash

          # List versions
          echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/avdmanager list device

          echo "Finished"
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          #!/usr/bin/env bash

          # Install AVD files
          echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install 'system-images;android-35;google_apis;x86_64'

          # Create emulator
          echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/avdmanager create avd -n xamarin_android_emulator -d "Nexus 10" -k 'system-images;android-35;google_apis;x86_64' --force

          echo "y" | $ANDROID_HOME/emulator/emulator -list-avds

          echo "Starting emulator"

          # Start emulator in background
          nohup $ANDROID_HOME/emulator/emulator -avd xamarin_android_emulator -no-snapshot -no-window -no-audio -no-boot-anim -accel on > /dev/null 2>&1 &
          $ANDROID_HOME/platform-tools/adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed | tr -d '\r') ]]; do sleep 1; done; input keyevent 82'

          $ANDROID_HOME/platform-tools/adb devices

          echo "Emulator started"